### ISSUE TITLE
For This youtube url , lib is not fetching article cause it's in diff formate structure.

### ISSUE THREAD

**Issue by rajumark** [prof18/RSS-Parser#103]
**Describe the bug**
https://www.youtube.com/feeds/videos.xml?channel_id=UCGp4UBwpTNegd_4nCpuBcow

I am trying to fetch this youtube url data for college project of my friend

**The link of the RSS Feed**
I Think issue is you have limited structure in  
[Article.kt](https://github.com/prof18/RSS-Parser/blob/master/rssparser/src/main/java/com/prof/rssparser/Article.kt)
Mostly rss source are working , thanks man , but some cause issue. 

is there any way? can we dynamic decide structure.

You can mark this bug as solved any time(no need my permission).

Thanks for reading this.

one more thing i would to like to add here , why we need context for getting data ? , 

`
val parser = Parser.Builder()
        .context(context)
`

-- One of your fan.

**Comment by prof18** [comment]
Hi! 
The context is required if you want to cache the feed. I f you are not interested in that, you can simply not set the context in the Builder. 

The youtube feed is an [Atom](https://en.wikipedia.org/wiki/Atom_(web_standard)), that's why isn't fully supported yet. But there's an initial work for it #94, so it could arrive in the future.

 If you need a youtube feed, you can also check out my other library: https://github.com/prof18/YoutubeParser

**Comment by prof18** [comment]
The Atom support is available since version 5.0.3
