### ISSUE TITLE
What's the right way to use v6 in Java?

### ISSUE THREAD

**Issue by ashishb** [prof18/RSS-Parser#160]
Can you please provide sample code to use v6 version in Java (not Kotlin)?
I am trying to migrate from v5 and am failing at the `feed fetching` step.

**Comment by prof18** [comment]
Hi! 
version 6 doesn't support Java anymore! You can still use version 5 in that scenario.

**Comment by prof18** [comment]
Hi,

because time is limited, and the ecosystem is Kotlin first now. You can still use the v5, or I've realized that you can still use the v6 from Java. You will need some Kotlin code as a wrapper to transform into `CompletableFuture` or `ListeneableFuture`. I've added some [docs](https://github.com/prof18/RSS-Parser?tab=readme-ov-file#using-the-library-in-a-java-project) about it and a [sample](https://github.com/prof18/RSS-Parser/tree/master/samples/java).
