### ISSUE TITLE
Creators instead of Authors

### ISSUE THREAD

**Issue by diyoyo** [prof18/RSS-Parser#36]
Please check this feed: 
http://feeds.rsc.org/rss/bm

The creators are in the xml, but appear nowhere in an Article object. even when looking at the "toString()" data.

Is there a way to ask for specific attributes?

Thanks.

**Comment by prof18** [comment]
That's because the keyword for the author is the following:

https://github.com/prof18/RSS-Parser/blob/5eb12ade03b05565312735a992450cbba63be530/rssparser/src/main/java/com/prof/rssparser/utils/RSSKeywords.kt#L25

For the time being there is no possibility to provide custom attributes. Maybe in the future, I could add it but for now, I don't know
