### ISSUE TITLE
Cached feed doesn't use charset

### ISSUE THREAD

**Issue by moshenskyi** [prof18/RSS-Parser#95]
**Describe the bug**
I use the RSS feed with the Ukrainian language. I have chosen the wrong charset in `Parser.Builder` and after I changed it and restarted the app it shows items with the wrong charset. I should clear the app's data to force applying the new charset.

It would be nice if we could force update the cache from the network if the charset changed

**The link of the RSS Feed**
https://loda.gov.ua/rss?lang=ua

**Comment by prof18** [comment]
Thanks for raising that issue and sorry for the late response. 

In that sense, it probably would make sense to pass the charset to the [getChannel](https://github.com/prof18/RSS-Parser/blob/master/rssparser/src/main/java/com/prof/rssparser/Parser.kt#L175) function. Otherwise that won't work if you are parsing multiple feeds
